<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>

        <ProjectReference Include="..\Zilor.AICopilot.Core.AiGateway\Zilor.AICopilot.Core.AiGateway.csproj" />

        <ProjectReference Include="..\Zilor.AICopilot.SharedKernel\Zilor.AICopilot.SharedKernel.csproj"/>
    </ItemGroup>

</Project>
