<Project Sdk="Aspire.AppHost.Sdk/13.0.0">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>0bf598ac-665f-44e2-a7d3-71381d83c636</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Zilor.AICopilot.HttpApi\Zilor.AICopilot.HttpApi.csproj" />
      <ProjectReference Include="..\Zilor.AICopilot.MigrationWorkApp\Zilor.AICopilot.MigrationWorkApp.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.0.0" />
    </ItemGroup>

</Project>
